[package]
name = "gotham_hello_world"
version = "0.1.0"
authors = ["Turki Jamaan <tjamaan.cmuq@gmail.com>"]

[dependencies]
hyper = "0.11"
gotham = "0.1"
gotham_derive = "0.1.0"
mime = "0.3"
log = "0.3"
serde = "1.0"
serde_derive = "1.0"